site_name: Bijux CLI
site_description: A modern, predictable Python CLI framework with plugins, DI, strict flag precedence, and an interactive REPL.
site_url: https://bijux.github.io/bijux-cli/
site_author: Bijan Mousavi
repo_url: https://github.com/bijux/bijux-cli
repo_name: bijux/bijux-cli
edit_uri: edit/main/docs/

strict: true
use_directory_urls: true
dev_addr: 127.0.0.1:8000

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/bijux_logo_hq.png
  favicon: assets/bijux_icon.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.instant
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
    - navigation.footer
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_section_style: list
            merge_init_into_class: true
            show_source: true
            show_if_no_docstring: false
            show_root_heading: true
            heading_level: 2
            separate_signature: true
            signature_crossrefs: true
            filters:
              - "!^_"
  - include-markdown:
      recursive: true
      dedent: true
      preserve_includer_indent: false
      trailing_newlines: true
      comments: false
      rewrite_relative_urls: true
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
  - gen-files:
      scripts:
        - scripts/helper_mkdocs.py
  - literate-nav:
      nav_file: nav.md
  - autorefs
  - redirects:

  - tags
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - social
  - offline
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - docs
        - .
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bijux/bijux-cli
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/bijux-cli/
  analytics:
    provider: plausible
    domain: bijux.github.io
  copyright:
    text: "© 2025 Bijan Mousavi"

extra_css:
  - assets/styles/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - src
  - scripts
  - config
  - tests
  - changelog.d
