[package]
name = "bijux_dag_runtime"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
authors = ["Bijan Mousavi"]

[dependencies]
bijux_dag_core = { path = "../bijux_dag_core" }
bijux_dag_artifacts = { path = "../bijux_dag_artifacts" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ctrlc = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
