pub(super) const REPO_SUITES: &[SuiteDef] = &[
    SuiteDef {
        id: "dependency-policy",
        description: "legacy workspace dependency reference check",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_missing_workspace_dependency_checks(),
    },
    SuiteDef {
        id: "dep-guard",
        description: "metadata dependency boundary check",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_dep_guard(),
    },
    SuiteDef {
        id: "ownership-public-modules",
        description: "crate public modules match ownership contract",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_crate_ownership_guard(),
    },
    SuiteDef {
        id: "cli-freeze",
        description: "freeze new top-level CLI commands",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_cli_command_freeze(),
    },
    SuiteDef {
        id: "adapter-freeze",
        description: "freeze runtime adapter kinds until split",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_adapter_kind_freeze(),
    },
    SuiteDef {
        id: "crate-manifest-policy",
        description: "crate manifest boundary policy checks",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_workspace_manifest_policy_guard(),
    },
    SuiteDef {
        id: "public-export-docs",
        description: "public exports require crate-doc contract mention",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_public_export_docs_guard(),
    },
    SuiteDef {
        id: "repo-docs",
        description: "doc root required governance contracts and budgets",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_repo_docs_guard(),
    },
    SuiteDef {
        id: "repo-source",
        description: "source layout policy and disallowed imports",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_repo_source_guard(),
    },
    SuiteDef {
        id: "root-directory-guard",
        description: "workspace root file layout guard",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_root_directory_guard(),
    },
    SuiteDef {
        id: "executable-guard",
        description: "checked-in executable source and docs files are forbidden",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_executable_guard(),
    },
    SuiteDef {
        id: "repo-manifests",
        description: "workspace Cargo manifest conventions",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_repo_manifests_guard(),
    },
    SuiteDef {
        id: "repo-api",
        description: "crate API docs coverage baseline",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_repo_api_guard(),
    },
    SuiteDef {
        id: "test-taxonomy",
        description: "test file naming taxonomy and e2e shell-out boundary",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_test_taxonomy_guard(),
    },
    SuiteDef {
        id: "test-classification",
        description: "test family classification report and category coverage",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_test_classification_report(),
    },
    SuiteDef {
        id: "test-policy",
        description: "schema fixtures runtime transitions and cache mode coverage policies",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_test_policy_guard(),
    },
    SuiteDef {
        id: "fault-summary",
        description: "fault class catalog coverage summary",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_fault_summary_report(),
    },
    SuiteDef {
        id: "performance-claims",
        description: "performance claims must reference benchmark evidence",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_performance_claims_guard(),
    },
    SuiteDef {
        id: "performance-evidence",
        description: "performance contract canonical scenarios and threshold policy coverage",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_performance_evidence_guard(),
    },
    SuiteDef {
        id: "resource-budgets-warning",
        description: "resource budget validation in warning mode",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_resource_budget_check(Path::new("artifacts/benchmarks/baseline.json"), false),
    },
    SuiteDef {
        id: "docs-governance",
        description: "docs taxonomy root budget and owners governance checks",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_docs_governance_guard(),
    },
    SuiteDef {
        id: "docs-links",
        description: "markdown local link and code anchor checker",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_docs_link_check(),
    },
    SuiteDef {
        id: "docs-schema-ref",
        description: "schema references in docs must resolve",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_docs_schema_reference_guard(),
    },
    SuiteDef {
        id: "docs-contract-ref",
        description: "crate README and CONTRACT references must resolve and be linked",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_docs_contract_reference_guard(),
    },
    SuiteDef {
        id: "docs-coverage",
        description: "docs coverage report for crates and commands",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_docs_coverage_report(),
    },
    SuiteDef {
        id: "contract-test-links",
        description: "contract docs must link at least one verifying test",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_contract_test_links_guard(),
    },
    SuiteDef {
        id: "contract-schema-owners",
        description: "schema files must be linked by owning contract docs",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_contract_schema_owner_guard(),
    },
    SuiteDef {
        id: "contract-command-ownership",
        description: "governed commands must be covered by exactly one command-surface section entry",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_contract_command_ownership_guard(),
    },
    SuiteDef {
        id: "contract-versioning-policy",
        description: "contract docs must declare versioning and change policy",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_contract_versioning_guard(),
    },
    SuiteDef {
        id: "contract-coverage-report",
        description: "report missing orphaned and stale contracts",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_contract_coverage_report(),
    },
    SuiteDef {
        id: "planner-alignment",
        description: "planner docs tests and schema alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_planner_alignment_guard(),
    },
    SuiteDef {
        id: "runtime-module-triage",
        description: "runtime module triage sacred boundaries and freeze policy alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_runtime_module_triage_guard(),
    },
    SuiteDef {
        id: "crate-boundary-foundation",
        description: "crate responsibility and dependency boundary enforcement",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_crate_boundary_foundation_guard(),
    },
    SuiteDef {
        id: "sacred-execution-flow",
        description: "sacred execution flow docs centralized hooks and engine flow tests alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_sacred_execution_flow_guard(),
    },
    SuiteDef {
        id: "runtime-semantics",
        description: "runtime semantics contract coverage for deterministic execution behavior",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_runtime_semantics_guard(),
    },
    SuiteDef {
        id: "test-trust-foundation",
        description: "runtime trust test catalog and contract coverage enforcement",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_test_trust_foundation_guard(),
    },
    SuiteDef {
        id: "test-trust-maintenance",
        description: "test trust ledger classification and semantic surface maintenance enforcement",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_test_trust_maintenance_guard(),
    },
    SuiteDef {
        id: "docs-config-reduction",
        description: "docs and config governance reduction contracts remain enforced",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_docs_config_reduction_guard(),
    },
    SuiteDef {
        id: "battle-suite-mandatory",
        description:
            "battle trust properties and scenario concentration remain mandatory in verification",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_battle_suite_mandatory_guard(),
    },
    SuiteDef {
        id: "naming-governance",
        description: "naming policy glossary and runtime naming lint enforcement",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_naming_governance_guard(),
    },
    SuiteDef {
        id: "scheduler-invariants",
        description: "scheduler contract and invariants test surfaces are present",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_scheduler_invariants_guard(),
    },
    SuiteDef {
        id: "state-machine-contract",
        description: "state machine contract docs enum variants and tests alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_state_machine_contract_guard(),
    },
    SuiteDef {
        id: "concurrency-model",
        description: "concurrency model docs tests and ledger alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_concurrency_model_guard(),
    },
    SuiteDef {
        id: "runtime-unsafe-audit",
        description: "runtime unsafe usage guard and auditability",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_runtime_unsafe_guard(),
    },
    SuiteDef {
        id: "backend-contract",
        description: "execution backend contract docs and parity test alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_backend_contract_guard(),
    },
    SuiteDef {
        id: "storage-boundaries",
        description: "storage contract docs and runtime path ownership checks",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_storage_boundary_guard(),
    },
    SuiteDef {
        id: "artifact-hardening",
        description: "run-directory hardening contracts and corruption fixtures are present",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_artifact_hardening_guard(),
    },
    SuiteDef {
        id: "observability-contract",
        description: "observability contract docs tests and required artifacts alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_observability_contract_guard(),
    },
    SuiteDef {
        id: "extensibility-contract",
        description: "extensibility contract docs schema tests and status report alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_extensibility_contract_guard(),
    },
    SuiteDef {
        id: "security-model",
        description: "security model docs enforcement tests and debt ledger alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_security_model_guard(),
    },
    SuiteDef {
        id: "container-remote-boundaries",
        description:
            "container remote and kubernetes docs must match implemented execution surfaces",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_container_remote_boundary_guard(),
    },
    SuiteDef {
        id: "batch-execution-boundaries",
        description:
            "batch execution docs and tests must align with simulated-not-implemented boundary",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_batch_execution_boundary_guard(),
    },
    SuiteDef {
        id: "operator-ux",
        description: "operator command index and run inspection UX contract alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_operator_ux_guard(),
    },
    SuiteDef {
        id: "authoring-ux",
        description: "authoring docs examples and fixture parse/validate alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_authoring_ux_guard(),
    },
    SuiteDef {
        id: "versioning-compatibility",
        description: "versioning model fixtures migration policy and no-drift enforcement",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_versioning_compatibility_guard(),
    },
    SuiteDef {
        id: "cache-evolution",
        description: "cache evolution docs fixtures and verification coverage alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_cache_evolution_guard(),
    },
    SuiteDef {
        id: "replay-contract",
        description: "replay semantics fixtures schema and explainability alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_replay_contract_guard(),
    },
    SuiteDef {
        id: "evidence-authority",
        description: "evidence metadata completeness and scenario path governance",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_evidence_metadata_validate(),
    },
    SuiteDef {
        id: "distributed-coordination",
        description: "distributed coordination model and simulation boundaries alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_distributed_coordination_guard(),
    },
    SuiteDef {
        id: "formal-invariants",
        description: "formal invariants registry docs tests and coverage alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_formal_invariants_guard(),
    },
    SuiteDef {
        id: "comparison-harness",
        description: "comparison harness scenarios baselines docs and anti-claim drift checks",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_comparison_harness_guard(),
    },
    SuiteDef {
        id: "adoption-surfaces",
        description: "adoption docs capabilities output and release verification alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_adoption_surfaces_guard(),
    },
    SuiteDef {
        id: "distribution-delivery",
        description: "distribution delivery goals for packages docs paths examples and release candidate",
        domain: "release",
        slow: true,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_release_artifact_verification_suite(),
    },
    SuiteDef {
        id: "anti-drift-governance",
        description: "anti-drift policy docs checks dashboard and trust evidence alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_anti_drift_governance_guard(),
    },
    SuiteDef {
        id: "multi-run-analytics",
        description: "multi-run analytics contracts commands schemas and tests alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_multi_run_analytics_guard(),
    },
    SuiteDef {
        id: "error-code-registry",
        description: "enumerate stable error codes and owner crates",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_error_code_registry_report(),
    },
    SuiteDef {
        id: "error-code-doc-tests",
        description: "public error codes require docs and test references",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_error_code_docs_tests_guard(),
    },
    SuiteDef {
        id: "config-lint",
        description: "checked-in config examples validate against config schemas",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_config_lint(),
    },
    SuiteDef {
        id: "config-drift",
        description: "docs precedence table matches effective resolver behavior",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_config_precedence_drift_guard(),
    },
    SuiteDef {
        id: "config-policy-determinism",
        description: "config precedence and policy determinism surfaces remain contract-aligned",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_config_policy_determinism_guard(),
    },
    SuiteDef {
        id: "ambient-env-guard",
        description: "ambient environment reads are limited to contract allowlist",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_ambient_env_guard(),
    },
    SuiteDef {
        id: "foundation-verification",
        description: "control-plane foundation coverage and ssot alignment",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_foundation_verification_guard(),
    },
    SuiteDef {
        id: "foundation-review",
        description: "foundation review evidence artifacts and reporting surfaces are present",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_foundation_review_guard(),
    },
    SuiteDef {
        id: "control-plane-surfaces",
        description: "control-plane verification command surfaces stay present",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_control_plane_surfaces_guard(),
    },
    SuiteDef {
        id: "repo-hygiene-suite",
        description: "repo hygiene suite aggregates core repository guardrails",
        domain: "governance",
        slow: false,
        internal: false,
        effect: CommandEffect::Validation,
        run: || run_repo_hygiene_suite_guard(),
    },
];
