[package]
name = "{{cookiecutter.plugin_namespace}}"
version = "{{cookiecutter.plugin_version}}"
edition = "{{cookiecutter.rust_edition}}"
license = "Apache-2.0"
description = "Rust executable for {{cookiecutter.project_name}} Bijux plugin"

[workspace]

[lib]
name = "{{cookiecutter.crate_name}}"
path = "src/lib.rs"

[[bin]]
name = "{{cookiecutter.plugin_namespace}}"
path = "src/main.rs"

[dependencies]
serde_json = "1"
