[package]
name = "bijux-dev-dag"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
bijux-dag-core = { path = "../bijux-dag-core" }
bijux-dag-artifacts = { path = "../bijux-dag-artifacts" }
bijux-dag-runtime = { path = "../bijux-dag-runtime" }
tempfile = { workspace = true }

[dev-dependencies]
bijux_dag_testkit = { package = "bijux-dag-testkit", path = "../bijux-dag-testkit" }
