[package]
name = "bijux-dev-dag"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
authors = ["Bijan Mousavi"]

[lints]
workspace = true

[lints.rust]
unused_crate_dependencies = "allow"

[dependencies]
clap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
bijux-dag-core = { path = "../bijux-dag-core" }
tempfile = { workspace = true }
