[package]
name = "bijux-dev-dag"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
authors = ["Bijan Mousavi"]

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
bijux-dag-core = { path = "../bijux-dag-core", version = "0.1.0" }
bijux-dag-artifacts = { path = "../bijux-dag-artifacts", version = "0.1.0" }
bijux-dag-runtime = { path = "../bijux-dag-runtime", version = "0.1.0" }
tempfile = { workspace = true }

[dev-dependencies]
bijux_dag_testkit = { package = "bijux-dag-testkit", path = "../bijux-dag-testkit" }
