[package]
name = "bijux-dag-cli"
version.workspace = true
description = "Installable command-line package for validating, running, replaying, and inspecting Bijux DAG graphs."
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage = "https://bijux.io/bijux-core/bijux-dag/"
documentation = "https://bijux.io/bijux-core/bijux-dag/packages/bijux-dag-cli/"
rust-version.workspace = true
readme = "README.md"
keywords = ["bijux", "dag", "cli", "workflow", "graphs"]
categories = ["command-line-interface", "development-tools"]

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
"bijux-dag-app" = { path = "../bijux-dag-app", version = "0.4.0" }

[dev-dependencies]
tempfile = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "bijux-dag"
path = "src/main.rs"
