[package]
name = "bijux-dag-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
bijux_dag_app = { package = "bijux-dag-app", path = "../bijux-dag-app" }

[dev-dependencies]
tempfile = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "bijux"
path = "src/main.rs"
