[package]
name = "bijux-dag-runtime"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bijux_dag_core = { package = "bijux-dag-core", path = "../bijux-dag-core", version = "0.3.5" }
bijux_dag_artifacts = { package = "bijux-dag-artifacts", path = "../bijux-dag-artifacts", version = "0.3.5" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ctrlc = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
bijux_dag_testkit = { package = "bijux-dag-testkit", path = "../bijux-dag-testkit", version = "0.3.5" }
