[package]
name = "bijux-dag-runtime"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
authors = ["Bijan Mousavi"]

[dependencies]
bijux_dag_core = { package = "bijux-dag-core", path = "../bijux-dag-core" }
bijux_dag_artifacts = { package = "bijux-dag-artifacts", path = "../bijux-dag-artifacts" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ctrlc = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
