[package]
name = "bijux-dag-testkit"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
authors = ["Bijan Mousavi"]

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
bijux_dag_core = { package = "bijux-dag-core", path = "../bijux-dag-core" }
bijux_dag_artifacts = { package = "bijux-dag-artifacts", path = "../bijux-dag-artifacts" }
