name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHONUNBUFFERED: "1"

jobs:
  tox:
    name: tox (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      # Python (tox-gh-actions maps 3.11 → py311 + lint/quality/security/api/docs/build/sbom/changelog/citation)
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # Tools needed by `make api`
      - uses: actions/setup-node@v4
        if: matrix.python-version == '3.11'
        with:
          node-version: "20"
          cache: "npm"

      - uses: actions/setup-java@v4
        if: matrix.python-version == '3.11'
        with:
          distribution: "temurin"
          java-version: "17"

      - run: python -m pip install -U pip tox tox-gh-actions
      - run: tox

      # Artifacts
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: .tox/**/coverage.xml
          if-no-files-found: ignore

      - name: Upload API log
        if: always() && matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: api-server-log
          path: artifacts/api-server.log
          if-no-files-found: ignore
