name: Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      ENABLE_SOCIAL_CARDS: "1"
    steps:
      - name: Checkout (full history for revision date plugin)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            mkdocs.yml

      - name: Install MkDocs toolchain
        run: |
          python -m pip install -U pip
          pip install ".[dev]"

      - name: Configure Git author (for gh-deploy commit)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build docs (strict)
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages (gh-pages)
        run: |
          mkdocs gh-deploy --force --strict --message "docs: deploy from ${GITHUB_SHA}"
