name: release-on-tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  actions: read
  packages: write
  pages: write
  id-token: write

jobs:
  release-crates:
    name: release-crates
    uses: ./.github/workflows/release-crates.yml
    with:
      release_tag: ${{ github.ref_name }}
    secrets: inherit

  release-pypi:
    name: release-pypi
    uses: ./.github/workflows/release-pypi.yml
    with:
      release_tag: ${{ github.ref_name }}
    secrets: inherit

  release-ghcr:
    name: release-ghcr
    uses: ./.github/workflows/release-ghcr.yml
    with:
      release_tag: ${{ github.ref_name }}
    secrets: inherit

  release-github:
    name: release-github
    uses: ./.github/workflows/release-github.yml
    with:
      release_tag: ${{ github.ref_name }}
    secrets: inherit

  deploy-docs:
    name: deploy-docs
    uses: ./.github/workflows/deploy-docs.yml
