mod catalog;
mod command_surface_behavior_executor;
mod compatibility_metadata_executor;
mod config_reports_executor;
mod crate_boundary_metrics_executor;
mod diagnostics_reports_executor;
mod governance_command_surface_executor;
mod governance_executor;
mod governance_spec;
mod governance_state_laws_executor;
mod history_behavior_reports_executor;
mod maintainer_control_plane_executor;
mod plugin_reports_executor;
mod release_and_plugin_executor;
mod release_and_plugin_spec;
mod release_reports_executor;
mod runner;
mod state_laws_reports_executor;
mod state_quality_reports_executor;
mod status_reports_executor;

pub(crate) use catalog::rows;
pub(crate) use runner::run;
